# Generated by Django 4.2.10 on 2025-09-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('url', models.URLField(unique=True)),
                ('date_posted', models.DateField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('title', 'company', 'location')},
            },
        ),
    ]
