# Generated by Django 4.2.10 on 2025-09-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_joblisting_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
